// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZ7JliZSxe8qVEEwC6MobqHm8OmON8K4',
    appId: '1:687846923785:web:95360d59613af9277f62d8',
    messagingSenderId: '687846923785',
    projectId: 'personalexpensestracker-bb2dc',
    authDomain: 'personalexpensestracker-bb2dc.firebaseapp.com',
    storageBucket: 'personalexpensestracker-bb2dc.appspot.com',
    measurementId: 'G-K9G2JQV8Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHHX6MC3fq5fWbGhUxepquj95hDh98zM',
    appId: '1:687846923785:android:3d7411a1ba4dbee77f62d8',
    messagingSenderId: '687846923785',
    projectId: 'personalexpensestracker-bb2dc',
    storageBucket: 'personalexpensestracker-bb2dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMfTCnuvhS1avW38agA7q6Ps3itgtfxQ0',
    appId: '1:687846923785:ios:16476460205c877d7f62d8',
    messagingSenderId: '687846923785',
    projectId: 'personalexpensestracker-bb2dc',
    storageBucket: 'personalexpensestracker-bb2dc.appspot.com',
    iosBundleId: 'com.example.personalExpensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMfTCnuvhS1avW38agA7q6Ps3itgtfxQ0',
    appId: '1:687846923785:ios:16476460205c877d7f62d8',
    messagingSenderId: '687846923785',
    projectId: 'personalexpensestracker-bb2dc',
    storageBucket: 'personalexpensestracker-bb2dc.appspot.com',
    iosBundleId: 'com.example.personalExpensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMZ7JliZSxe8qVEEwC6MobqHm8OmON8K4',
    appId: '1:687846923785:web:b94901136c16a3707f62d8',
    messagingSenderId: '687846923785',
    projectId: 'personalexpensestracker-bb2dc',
    authDomain: 'personalexpensestracker-bb2dc.firebaseapp.com',
    storageBucket: 'personalexpensestracker-bb2dc.appspot.com',
    measurementId: 'G-GTQ01PEE3X',
  );
}
